# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: first_arm
  joint_model_group_pose: first_arm_default
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - First_arm_joint_base_to_one
    - First_arm_joint_one_to_two
    - First_arm_joint_two_to_three
    - First_arm_joint_three_to_four
    - First_arm_gripper_joint
    - Second_arm_joint_base_to_one
    - Second_arm_joint_one_to_two
    - Second_arm_joint_two_to_three
    - Second_arm_joint_three_to_four
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: first_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - First_arm_joint_base_to_one
      - First_arm_joint_one_to_two
      - First_arm_joint_two_to_three
      - First_arm_joint_three_to_four
      - First_arm_gripper_joint
  - name: second_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - Second_arm_joint_base_to_one
      - Second_arm_joint_one_to_two
      - Second_arm_joint_two_to_three
      - Second_arm_joint_three_to_four